[package]
name = "baddyCli"
version = "0.1.1"
edition = "2024"

[dependencies]
colored = "3.0.0"
reqwest = { version = "0.12.15",features=["blocking","json"] }
serde = "1.0.219"
serde_json = "1.0.140"
